import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { PageHeading, PriorityBadge, SeverityBadge, StatusBadge, formatDate } from "@/components/buglens";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, Ban, Bug, Check, FileWarning, Search, ShieldAlert, Trash2, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const colors:Record<string,string>={CRITICAL:"#e11d48",HIGH:"#f97316",MEDIUM:"#f59e0b",LOW:"#94a3b8"};
export default function Admin() {
  const {user}=useAuth();
  const [,setLocation]=useLocation();
  const [search,setSearch]=useState("");
  const searchInput=useMemo(()=>({search}),[search]);
  const stats=trpc.buglens.admin.stats.useQuery(undefined,{enabled:user?.role==="admin",retry:false});
  const users=trpc.buglens.admin.users.useQuery(searchInput,{enabled:user?.role==="admin",retry:false});
  const reports=trpc.buglens.admin.reports.useQuery(undefined,{enabled:user?.role==="admin",retry:false});
  const utils=trpc.useUtils();
  const disable=trpc.buglens.admin.setUserDisabled.useMutation({onSuccess:async(_,variables)=>{toast.success(variables.disabled?"User disabled.":"User enabled.");await utils.buglens.admin.users.invalidate();},onError:error=>toast.error(error.message)});
  const remove=trpc.buglens.admin.deleteReport.useMutation({onSuccess:async()=>{toast.success("Report removed.");await Promise.all([utils.buglens.admin.reports.invalidate(),utils.buglens.admin.stats.invalidate()]);},onError:error=>toast.error(error.message)});

  return <DashboardLayout><div className="mx-auto max-w-[1500px]"><PageHeading eyebrow="Organization controls" title="Admin console" description="Monitor system-wide activity and manage access to the BugLens workspace." />
    {user?.role!=="admin"?<div className="rounded-2xl border border-amber-200 bg-amber-50 p-8 text-center"><ShieldAlert className="mx-auto h-8 w-8 text-amber-600"/><h2 className="mt-3 text-sm font-semibold text-slate-900">Administrator role required</h2><p className="mt-1 text-xs text-slate-600">Your account does not have access to system-wide user or report data.</p><Button onClick={()=>setLocation("/dashboard")} variant="outline" className="mt-4 h-9 rounded-lg text-xs">Return to overview</Button></div>:<>
      {stats.error&&<div role="alert" className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-xs text-rose-700">{stats.error.message}</div>}
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{label:"Total users",value:stats.data?.totalUsers,icon:Users,accent:"bg-indigo-50 text-indigo-700"},{label:"Total reports",value:stats.data?.totalReports,icon:Bug,accent:"bg-sky-50 text-sky-700"},{label:"AI analyses",value:stats.data?.totalAnalyses,icon:Activity,accent:"bg-emerald-50 text-emerald-700"},{label:"Failed analyses",value:stats.data?.failedAnalyses,icon:FileWarning,accent:"bg-rose-50 text-rose-700"}].map(({label,value,icon:Icon,accent})=><div key={label} className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs text-slate-500">{label}</p><p className="mt-3 text-2xl font-semibold text-slate-900">{stats.isLoading?<span className="inline-block h-7 w-14 animate-pulse rounded bg-slate-100"/>:value??0}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${accent}`}><Icon className="h-[18px] w-[18px]"/></span></div></div>)}</section>
      <section className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-900">System severity distribution</h2><p className="mt-1 text-xs text-slate-400">Across analyzed reports</p><div className="mt-4 h-[225px]">{stats.isLoading?<div className="h-full animate-pulse rounded-xl bg-slate-50"/>:<ResponsiveContainer width="100%" height="100%"><BarChart data={stats.data?.severity??[]} margin={{top:8,right:8,left:0,bottom:0}}><CartesianGrid stroke="#eef1f6" vertical={false}/><XAxis dataKey="name" tick={{fill:"#64748b",fontSize:10}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fill:"#94a3b8",fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{border:"1px solid #e2e8f0",borderRadius:10,fontSize:12}}/><Bar dataKey="value" name="Reports" radius={[5,5,0,0]} maxBarSize={48}>{(stats.data?.severity??[]).map(item=><Cell key={item.name} fill={colors[item.name]??"#6366f1"}/>)}</Bar></BarChart></ResponsiveContainer>}</div></div><div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-900">Most common categories</h2><p className="mt-1 text-xs text-slate-400">Organization-wide issue clustering</p><div className="mt-4 space-y-3">{stats.isLoading?Array.from({length:6},(_,i)=><div key={i} className="h-6 animate-pulse rounded bg-slate-50"/>):stats.data?.commonCategories.length?stats.data.commonCategories.map(item=>{const max=Math.max(...stats.data!.commonCategories.map(x=>x.value),1);return <div key={item.name}><div className="mb-1 flex justify-between text-[10px]"><span className="font-medium text-slate-700">{item.name.replaceAll("_"," ")}</span><span className="text-slate-400">{item.value}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{width:`${Math.max(3,(item.value/max)*100)}%`}}/></div></div>}):<p className="py-8 text-center text-xs text-slate-400">No completed AI analyses yet.</p>}</div></div></section>
      <section className="mt-4 rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-900">Daily analysis outcomes</h2><p className="mt-1 text-xs text-slate-400">Successful and failed analysis runs · last 14 days</p><div className="mt-4 h-[230px]">{stats.isLoading?<div className="h-full animate-pulse rounded-xl bg-slate-50"/>:<ResponsiveContainer width="100%" height="100%"><LineChart data={stats.data?.dailyVolume??[]} margin={{top:8,right:12,left:0,bottom:0}}><CartesianGrid stroke="#eef1f6" vertical={false}/><XAxis dataKey="date" tickFormatter={value=>new Date(`${value}T00:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})} tick={{fill:"#94a3b8",fontSize:10}} axisLine={false} tickLine={false} interval={2}/><YAxis allowDecimals={false} tick={{fill:"#94a3b8",fontSize:10}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={value=>new Date(`${value}T00:00:00`).toLocaleDateString()} contentStyle={{border:"1px solid #e2e8f0",borderRadius:10,fontSize:12}}/><Line type="monotone" dataKey="value" name="Outcomes" stroke="#6366f1" strokeWidth={2.5} dot={{r:3,fill:"#6366f1"}} activeDot={{r:5}}/></LineChart></ResponsiveContainer>}</div></section>
      <section className="mt-5 rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-sm font-semibold text-slate-900">Workspace users</h2><p className="mt-1 text-xs text-slate-400">Up to 200 accounts · disabling takes effect on the next API request</p></div><div className="relative w-full sm:max-w-[290px]"><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name or email" className="h-9 rounded-lg border-slate-200 pl-9 text-xs"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[670px] text-left"><thead><tr className="border-b border-slate-100 text-[9px] uppercase tracking-wider text-slate-400"><th className="pb-3 pl-2 font-semibold">User</th><th className="pb-3 font-semibold">Role</th><th className="pb-3 font-semibold">Joined</th><th className="pb-3 font-semibold">Status</th><th className="pb-3 pr-2 text-right font-semibold">Access</th></tr></thead><tbody>{users.isLoading?Array.from({length:3},(_,i)=><tr key={i}><td colSpan={5} className="py-3"><div className="h-5 animate-pulse rounded bg-slate-50"/></td></tr>):users.data?.map(account=><tr key={account.id} className="border-b border-slate-50 last:border-0"><td className="py-3.5 pl-2"><p className="text-xs font-semibold text-slate-800">{account.name||"Unnamed user"}</p><p className="mt-1 text-[10px] text-slate-400">{account.email||"No email"}</p></td><td className="py-3.5"><span className={`rounded-md px-2 py-1 text-[9px] font-semibold ${account.role==="admin"?"bg-indigo-50 text-indigo-700":"bg-slate-100 text-slate-600"}`}>{account.role.toUpperCase()}</span></td><td className="py-3.5 text-[10px] text-slate-500">{formatDate(account.createdAt)}</td><td className="py-3.5"><span className={`text-[10px] font-medium ${account.disabled?"text-rose-600":"text-emerald-600"}`}>{account.disabled?"Disabled":"Active"}</span></td><td className="py-3.5 pr-2 text-right"><Button variant="outline" size="sm" disabled={disable.isPending||account.id===user.id} onClick={()=>disable.mutate({id:account.id,disabled:!account.disabled})} className="h-8 rounded-lg border-slate-200 text-[10px]">{account.disabled?<><Check className="mr-1.5 h-3 w-3"/>Enable</>:<><Ban className="mr-1.5 h-3 w-3"/>Disable</>}</Button></td></tr>)}</tbody></table></div>{!users.isLoading&&users.data?.length===0&&<p className="py-7 text-center text-xs text-slate-400">No matching users.</p>}</section>
      <section className="mt-5 rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4"><h2 className="text-sm font-semibold text-slate-900">All reports</h2><p className="mt-1 text-xs text-slate-400">Most recent 200 workspace reports</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b border-slate-100 text-[9px] uppercase tracking-wider text-slate-400"><th className="py-3 pl-2 font-semibold">Report</th><th className="py-3 font-semibold">Owner</th><th className="py-3 font-semibold">Severity</th><th className="py-3 font-semibold">Priority</th><th className="py-3 font-semibold">Status</th><th className="py-3 font-semibold">Date</th><th className="py-3 pr-2 text-right font-semibold">Moderation</th></tr></thead><tbody>{reports.isLoading?Array.from({length:4},(_,i)=><tr key={i}><td colSpan={7} className="py-3"><div className="h-5 animate-pulse rounded bg-slate-50"/></td></tr>):reports.data?.map(({report,summary,ownerName,ownerEmail})=><tr key={report.id} className="border-b border-slate-50 last:border-0"><td className="max-w-[250px] truncate py-3.5 pl-2"><Link href={`/reports/${report.id}`} className="text-xs font-semibold text-slate-800 hover:text-indigo-700">{report.title}<ArrowRight className="ml-1.5 inline h-3 w-3 text-slate-300"/></Link></td><td className="py-3.5"><p className="text-[10px] text-slate-700">{ownerName||"—"}</p><p className="mt-1 text-[9px] text-slate-400">{ownerEmail||""}</p></td><td className="py-3.5"><SeverityBadge value={summary?.severity}/></td><td className="py-3.5"><PriorityBadge value={summary?.priority}/></td><td className="py-3.5"><StatusBadge value={report.status}/></td><td className="py-3.5 text-[10px] text-slate-400">{formatDate(report.createdAt)}</td><td className="py-3.5 pr-2 text-right"><button title="Remove report" onClick={()=>{if(window.confirm(`Permanently delete “${report.title}”?`))remove.mutate({id:report.id});}} disabled={remove.isPending} className="grid h-8 w-8 place-items-center rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-3.5 w-3.5"/></button></td></tr>)}</tbody></table></div>{reports.data?.length===0&&!reports.isLoading&&<p className="py-7 text-center text-xs text-slate-400">No reports found.</p>}</section>
      <div className="mt-4 flex items-center gap-2 rounded-xl border border-amber-100 bg-amber-50/60 p-3"><ShieldAlert className="h-4 w-4 shrink-0 text-amber-600"/><p className="text-[10px] leading-5 text-slate-600">Administrator visibility is organization-wide. Only use report deletion for inappropriate content or policy enforcement.</p></div>
    </>}
  </div></DashboardLayout>;
}
