import DashboardLayout from "@/components/DashboardLayout";
import { PageHeading, StatusBadge, formatDate } from "@/components/buglens";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { AlertCircle, ArrowRight, CheckCircle2, CircleHelp, FileSpreadsheet, FileUp, LoaderCircle, RefreshCw, Sparkles, Upload, X } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

type CsvReport={title:string;description:string;environment?:string};
function parseCsv(text:string):string[][] {
  const rows:string[][]=[];let row:string[]=[];let field="";let quoted=false;
  const source=text.replace(/^\uFEFF/,"");
  for(let i=0;i<source.length;i+=1){const char=source[i];if(quoted){if(char==='"'&&source[i+1]==='"'){field+='"';i+=1;}else if(char==='"'){quoted=false;}else field+=char;}else if(char==='"'){quoted=true;}else if(char===","){row.push(field);field="";}else if(char==="\n"||char==="\r"){if(char==="\r"&&source[i+1]==="\n")i+=1;row.push(field);if(row.some(cell=>cell.trim()))rows.push(row);row=[];field="";}else field+=char;}
  if(quoted)throw new Error("The CSV has an unclosed quoted field.");
  row.push(field);if(row.some(cell=>cell.trim()))rows.push(row);return rows;
}
function decodeCsv(text:string):CsvReport[]{const rows=parseCsv(text);if(rows.length<2)throw new Error("Add a header row and at least one report.");const headers=rows[0].map(value=>value.trim().toLowerCase());const titleIndex=headers.indexOf("title"),descriptionIndex=headers.indexOf("description"),environmentIndex=headers.indexOf("environment");if(titleIndex<0||descriptionIndex<0)throw new Error("CSV needs title and description columns. Environment is optional.");if(rows.length-1>100)throw new Error("A batch can contain up to 100 reports.");return rows.slice(1).map((row,index)=>{const title=row[titleIndex]?.trim()??"",description=row[descriptionIndex]?.trim()??"",environment=environmentIndex>=0?row[environmentIndex]?.trim()??"":"";if(title.length<3)throw new Error(`Row ${index+2}: title must contain at least 3 characters.`);if(description.length<10)throw new Error(`Row ${index+2}: description must contain at least 10 characters.`);if(title.length>255||description.length>20000||environment.length>1000)throw new Error(`Row ${index+2}: one or more fields exceed allowed limits.`);return{title,description,environment};});}

export default function Batch() {
  const fileRef=useRef<HTMLInputElement>(null);
  const utils=trpc.useUtils();
  const list=trpc.buglens.batch.list.useQuery(undefined,{refetchInterval:5000});
  const [fileName,setFileName]=useState("");
  const [draft,setDraft]=useState<CsvReport[]>([]);
  const [selectedId,setSelectedId]=useState<number|null>(null);
  const [problem,setProblem]=useState("");
  const [creating,setCreating]=useState(false);
  const [isProcessing,setIsProcessing]=useState(false);
  const [progress,setProgress]=useState({done:0,total:0,failed:0});
  const [batchName,setBatchName]=useState("");
  const detail=trpc.buglens.batch.get.useQuery({id:selectedId??0},{enabled:selectedId!==null,refetchInterval:isProcessing?2500:false});
  const create=trpc.buglens.batch.create.useMutation();
  const start=trpc.buglens.batch.start.useMutation();
  const analyze=trpc.buglens.reports.analyze.useMutation();
  const batches=list.data??[];
  const selected=detail.data;
  const durationNotice=useMemo(()=>draft.length>20?"Large batches can take several minutes. You can return to this page to resume.":"Each report is saved before analysis and can be resumed if you leave.",[draft.length]);

  async function chooseFile(file?:File){if(!file)return;setProblem("");if(file.size>2*1024*1024){setProblem("CSV files must be 2 MB or smaller.");return;}if(!file.name.toLowerCase().endsWith(".csv")){setProblem("Choose a .csv file.");return;}try{const rows=decodeCsv(await file.text());setFileName(file.name);setBatchName(file.name.replace(/\.csv$/i,"").slice(0,255));setDraft(rows);setSelectedId(null);}catch(error){setDraft([]);setProblem(error instanceof Error?error.message:"Unable to read this CSV file.");}}

  async function createBatch(){if(!draft.length)return;setCreating(true);setProblem("");try{const result=await create.mutateAsync({name:batchName.trim()||fileName||"Bug report import",reports:draft});setSelectedId(result.id);setProgress({done:0,total:draft.length,failed:0});setDraft([]);toast.success(`${draft.length} reports saved to batch.`);await utils.buglens.batch.list.invalidate();void processBatch(result.id);}catch(error){setProblem(error instanceof Error?error.message:"Unable to create batch.");}finally{setCreating(false);}}

  async function processBatch(batchId:number){if(isProcessing)return;setIsProcessing(true);setProblem("");try{const result=await start.mutateAsync({id:batchId});const completed=result.reports.filter(report=>report.status==="ANALYZED").length;let failed=result.reports.filter(report=>report.status==="FAILED").length;let done=completed;setProgress({done,total:result.reports.length,failed});for(const report of result.reports){if(report.status==="ANALYZED")continue;try{await analyze.mutateAsync({id:report.id});}catch{failed+=1;}done+=1;setProgress({done,total:result.reports.length,failed});}await Promise.all([utils.buglens.batch.get.invalidate({id:batchId}),utils.buglens.batch.list.invalidate(),utils.buglens.dashboard.stats.invalidate()]);toast.success(failed?`Batch finished with ${failed} failed report${failed===1?"":"s"}.`:"All reports were analyzed.");}catch(error){setProblem(error instanceof Error?error.message:"Batch processing was interrupted. Resume it when ready.");toast.error("Batch processing stopped. Your saved progress is safe.");}finally{setIsProcessing(false);}}

  return <DashboardLayout><div className="mx-auto max-w-[1250px]"><PageHeading eyebrow="Bulk triage" title="Batch processing" description="Import bug reports from a CSV and process them sequentially with progress saved to your workspace." />
    <div className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
      <Card className="h-fit rounded-2xl border-slate-200/80 bg-white shadow-sm"><CardHeader className="border-b border-slate-100 pb-4"><div className="flex items-center justify-between"><div><CardTitle className="text-sm">Import CSV</CardTitle><p className="mt-1 text-xs text-slate-400">Up to 100 reports · 2 MB maximum</p></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><FileSpreadsheet className="h-4 w-4"/></span></div></CardHeader><CardContent className="p-5">
        <div onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();void chooseFile(event.dataTransfer.files[0]);}} className="rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50/60 px-5 py-9 text-center transition-colors hover:border-indigo-300 hover:bg-indigo-50/30"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-white text-indigo-600 shadow-sm"><Upload className="h-5 w-5"/></div><p className="mt-4 text-sm font-semibold text-slate-800">Drop your CSV here</p><p className="mt-1 text-xs text-slate-500">or choose a file from your device</p><Button type="button" variant="outline" onClick={()=>fileRef.current?.click()} className="mt-4 h-9 rounded-lg border-slate-200 bg-white text-xs font-semibold">Browse files</Button><input ref={fileRef} type="file" accept=".csv,text/csv" className="hidden" onChange={event=>void chooseFile(event.target.files?.[0])}/><p className="mt-4 text-[10px] text-slate-400">Required columns: title, description · Optional: environment</p></div>
        <div className="mt-4 rounded-xl border border-slate-100 bg-white p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold text-slate-700">Expected CSV format</p><a href="data:text/csv;charset=utf-8,title%2Cdescription%2Cenvironment%0A%22Checkout%20freezes%22%2C%22The%20payment%20page%20freezes%20after%20clicking%20pay%22%2C%22Chrome%20%2F%20Windows%22" download="buglens-example.csv" className="text-[10px] font-semibold text-indigo-600 hover:text-indigo-700">Download sample</a></div><pre className="mt-2 overflow-x-auto text-[9px] leading-5 text-slate-500">title,description,environment<br/>"Checkout freezes","Payment page freezes after clicking pay","Chrome / Windows"</pre></div>
        {problem&&<div role="alert" className="mt-4 flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 px-3.5 py-3 text-xs text-rose-700"><AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0"/>{problem}</div>}
        {draft.length>0&&<div className="mt-4 rounded-xl border border-indigo-100 bg-indigo-50/40 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-slate-800">{fileName}</p><p className="mt-1 text-[10px] text-slate-500">{draft.length} valid reports ready to save</p></div><button onClick={()=>{setDraft([]);setFileName("");}} aria-label="Clear CSV" className="text-slate-400 hover:text-slate-700"><X className="h-4 w-4"/></button></div><label className="mt-4 block space-y-1.5 text-[10px] font-semibold text-slate-600">Batch name<input value={batchName} maxLength={255} onChange={e=>setBatchName(e.target.value)} className="h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs font-normal outline-none focus:border-indigo-300 focus:ring-2 focus:ring-indigo-100"/></label><div className="mt-3 max-h-32 space-y-1 overflow-auto rounded-lg bg-white/80 p-2">{draft.slice(0,5).map((report,index)=><p key={index} className="truncate text-[10px] text-slate-600">{index+1}. {report.title}</p>)}{draft.length>5&&<p className="text-[10px] text-slate-400">+{draft.length-5} additional reports</p>}</div><p className="mt-3 text-[10px] leading-4 text-slate-500">{durationNotice}</p><Button onClick={()=>void createBatch()} disabled={creating} className="mt-4 h-10 w-full rounded-lg bg-indigo-600 text-xs font-semibold hover:bg-indigo-700">{creating?<LoaderCircle className="mr-2 h-4 w-4 animate-spin"/>:<FileUp className="mr-2 h-4 w-4"/>}Save &amp; begin batch</Button></div>}
      </CardContent></Card>

      <div className="space-y-4"><Card className="rounded-2xl border-slate-200/80 bg-white shadow-sm"><CardHeader className="pb-3"><div className="flex items-center justify-between"><div><CardTitle className="text-sm">Processing progress</CardTitle><p className="mt-1 text-xs text-slate-400">Each report is saved before processing starts.</p></div>{isProcessing&&<span className="flex items-center gap-1.5 rounded-full bg-blue-50 px-2.5 py-1 text-[9px] font-semibold text-blue-700"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-blue-500"/>PROCESSING</span>}</div></CardHeader><CardContent className="space-y-4 pt-0">
        {selected?<><div className="flex items-start justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50/70 p-3"><div className="min-w-0"><p className="truncate text-xs font-semibold text-slate-800">{selected.name}</p><p className="mt-1 text-[10px] text-slate-400">Created {formatDate(selected.createdAt)} · {selected.totalReports} reports</p></div><StatusBadge value={selected.status}/></div><Progress value={selected.totalReports?Math.min(100,(selected.processedReports/selected.totalReports)*100):0} className="h-2"/><div className="grid grid-cols-3 gap-2"><CountTile label="Total" value={selected.totalReports} /><CountTile label="Processed" value={selected.processedReports} /><CountTile label="Failed" value={selected.failedReports} /></div>{progress.total>0&&isProcessing&&<p className="text-[10px] text-slate-500">This session: {progress.done} / {progress.total} finished · {progress.failed} failed</p>}{!isProcessing&&(selected.status==="PROCESSING"||selected.status==="QUEUED"||selected.failedReports>0)&&<Button onClick={()=>void processBatch(selected.id)} className="h-9 w-full rounded-lg bg-indigo-600 text-xs">{selected.status==="PROCESSING"?"Resume remaining reports":"Start or retry batch"}<ArrowRight className="ml-2 h-3.5 w-3.5"/></Button>}<div className="max-h-[330px] divide-y divide-slate-100 overflow-y-auto rounded-xl border border-slate-100">{selected.reports.map(({report,summary})=><Link key={report.id} href={`/reports/${report.id}`} className="flex items-center gap-2.5 px-3 py-2.5 transition-colors hover:bg-slate-50"><span className={`h-2 w-2 shrink-0 rounded-full ${report.status==="ANALYZED"?"bg-emerald-500":report.status==="FAILED"?"bg-rose-500":report.status==="ANALYZING"?"animate-pulse bg-blue-500":"bg-slate-300"}`}/><span className="min-w-0 flex-1 truncate text-[10px] font-medium text-slate-700">{report.title}</span><span className="hidden text-[9px] text-slate-400 sm:block">{summary?.severity??""}</span><StatusBadge value={report.status}/></Link>)}</div></>:<div className="rounded-xl border border-dashed border-slate-200 py-10 text-center"><div className="mx-auto grid h-10 w-10 place-items-center rounded-xl bg-slate-50 text-slate-400"><CircleHelp className="h-5 w-5"/></div><p className="mt-3 text-xs font-semibold text-slate-800">No batch selected</p><p className="mx-auto mt-1 max-w-xs text-[10px] leading-5 text-slate-500">Import a CSV to create a saved batch. Processing progress is stored, so you can resume later.</p></div>}
      </CardContent></Card>
      <Card className="rounded-2xl border-slate-200/80 bg-white shadow-sm"><CardHeader className="flex flex-row items-center justify-between pb-3"><div><CardTitle className="text-sm">Recent batches</CardTitle><p className="mt-1 text-xs text-slate-400">Saved to your workspace</p></div><button onClick={()=>void list.refetch()} className="text-slate-400 hover:text-indigo-600"><RefreshCw className={`h-3.5 w-3.5 ${list.isFetching?"animate-spin":""}`}/></button></CardHeader><CardContent className="pt-0">{list.isLoading?<div className="h-20 animate-pulse rounded-xl bg-slate-50"/>:batches.length===0?<p className="py-6 text-center text-[10px] text-slate-400">Your imported batches will appear here.</p>:<div className="divide-y divide-slate-100">{batches.slice(0,6).map(batch=><button key={batch.id} onClick={()=>{setSelectedId(batch.id);setProgress({done:batch.processedReports,total:batch.totalReports,failed:batch.failedReports});}} className={`flex w-full items-center gap-3 py-3 text-left ${selectedId===batch.id?"":"hover:bg-slate-50"}`}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-indigo-50 text-indigo-600"><FileSpreadsheet className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="block truncate text-[11px] font-semibold text-slate-800">{batch.name}</span><span className="mt-1 block text-[9px] text-slate-400">{batch.totalReports} reports · {formatDate(batch.createdAt)}</span></span><StatusBadge value={batch.status}/></button>)}</div>}</CardContent></Card>
      <div className="flex items-start gap-2 rounded-xl border border-blue-100 bg-blue-50/60 p-3"><Sparkles className="mt-0.5 h-3.5 w-3.5 shrink-0 text-blue-600"/><p className="text-[10px] leading-5 text-slate-600">For reliability, batch items are analyzed one at a time. Closing this page stops the current run; the saved batch can be resumed when you return.</p></div>
      </div>
    </div>
  </div></DashboardLayout>;
}
function CountTile({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 px-3 py-2.5"><p className="text-[9px] text-slate-400">{label}</p><p className="mt-1 text-lg font-semibold text-slate-800">{value}</p></div>}
