import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeading, PriorityBadge, SeverityBadge, SectionHeading, StatusBadge, formatDate } from "@/components/buglens";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { ArrowDownRight, ArrowRight, ArrowUpRight, Bug, CircleAlert, Clock3, FileCheck2, Plus, RefreshCw, ShieldAlert, Sparkles } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "wouter";

const recentInput = { page: 1, pageSize: 6, search: "", sort: "newest" as const };
const palette: Record<string, string> = { CRITICAL: "#e11d48", HIGH: "#f97316", MEDIUM: "#f59e0b", LOW: "#94a3b8", P0: "#e11d48", P1: "#f97316", P2: "#f59e0b", P3: "#94a3b8", AUTH: "#6366f1", PAYMENT: "#f43f5e", UI_UX: "#0ea5e9", PERFORMANCE: "#8b5cf6", DATA: "#14b8a6", API: "#f59e0b", SECURITY: "#ef4444", INFRASTRUCTURE: "#64748b", OTHER: "#94a3b8" };
const pretty = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, c => c.toUpperCase());

export default function Dashboard() {
  const stats = trpc.buglens.dashboard.stats.useQuery(undefined, { retry: false });
  const recent = trpc.buglens.reports.list.useQuery(recentInput, { retry: false });
  const refreshing = async () => { await Promise.all([stats.refetch(), recent.refetch()]); };
  const cards = [
    { label: "Total reports", value: stats.data?.totalReports, icon: Bug, note: `${stats.data?.reportsThisWeek ?? 0} created in the last 7 days`, accent: "text-indigo-600", bg: "bg-indigo-50" },
    { label: "AI analyzed", value: stats.data?.analyzedReports, icon: FileCheck2, note: "Structured summaries ready", accent: "text-emerald-600", bg: "bg-emerald-50" },
    { label: "Awaiting analysis", value: stats.data?.pendingReports, icon: Clock3, note: "Pending or processing", accent: "text-amber-600", bg: "bg-amber-50" },
    { label: "High severity", value: (stats.data?.highSeverityBugs ?? 0) + (stats.data?.criticalBugs ?? 0), icon: ShieldAlert, note: `${stats.data?.criticalBugs ?? 0} critical impact`, accent: "text-rose-600", bg: "bg-rose-50" },
  ];

  return <DashboardLayout><div className="mx-auto max-w-[1450px]">
    <PageHeading eyebrow="Your engineering workspace" title="Triage overview" description="A current view of the issues your team has brought into focus." action={<Button variant="outline" onClick={() => void refreshing()} disabled={stats.isFetching} className="h-9 rounded-lg border-slate-200 bg-white text-xs"><RefreshCw className={`mr-2 h-3.5 w-3.5 ${stats.isFetching ? "animate-spin" : ""}`} />Refresh</Button>} />
    {(stats.error || recent.error) && <div role="alert" className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{stats.error?.message || recent.error?.message || "Unable to load workspace data."}</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,icon:Icon,note,accent,bg},index)=><Card key={label} className="overflow-hidden rounded-2xl border-slate-200/80 bg-white shadow-sm shadow-slate-900/[0.02]"><CardContent className="p-4 sm:p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-3 text-[27px] font-semibold tracking-tight text-slate-950">{stats.isLoading ? <span className="inline-block h-8 w-14 animate-pulse rounded-md bg-slate-100"/> : value ?? 0}</p></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${bg} ${accent}`}><Icon className="h-[18px] w-[18px]"/></div></div><p className="mt-3 flex items-center gap-1.5 text-[11px] text-slate-400">{index===0&&<ArrowUpRight className="h-3 w-3 text-emerald-500"/>}{index===3&&<CircleAlert className="h-3 w-3 text-rose-500"/>}{note}</p></CardContent></Card>)}</section>

    <section className="mt-5 grid gap-4 xl:grid-cols-[1.55fr_1fr]">
      <Card className="rounded-2xl border-slate-200/80 bg-white shadow-sm shadow-slate-900/[0.02]"><CardHeader className="flex flex-row items-start justify-between pb-0"><div><CardTitle className="text-sm font-semibold text-slate-900">Report activity</CardTitle><p className="mt-1 text-xs text-slate-400">New reports across the last 14 days</p></div><span className="rounded-md bg-slate-50 px-2 py-1 text-[10px] font-medium text-slate-500">Last 14 days</span></CardHeader><CardContent className="pt-4"><div className="h-[235px] w-full">{stats.isLoading ? <div className="h-full animate-pulse rounded-xl bg-slate-50"/> : <ResponsiveContainer width="100%" height="100%"><BarChart data={stats.data?.overTime ?? []} margin={{ top: 10, right: 5, left: -20, bottom: 0 }}><CartesianGrid stroke="#eef1f6" vertical={false} /><XAxis dataKey="date" tickFormatter={value=>new Date(`${value}T00:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})} tick={{ fill: "#94a3b8", fontSize: 10 }} axisLine={false} tickLine={false} interval={2} /><YAxis allowDecimals={false} tick={{ fill: "#94a3b8", fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: "#f5f6fa" }} labelFormatter={value=>new Date(`${value}T00:00:00`).toLocaleDateString()} contentStyle={{ border: "1px solid #e2e8f0", borderRadius: 10, fontSize: 12 }} /><Bar dataKey="value" name="Reports" fill="#6366f1" radius={[4,4,0,0]} maxBarSize={22} /></BarChart></ResponsiveContainer>}</div></CardContent></Card>
      <Card className="rounded-2xl border-slate-200/80 bg-white shadow-sm shadow-slate-900/[0.02]"><CardHeader className="pb-0"><CardTitle className="text-sm font-semibold text-slate-900">Severity distribution</CardTitle><p className="mt-1 text-xs text-slate-400">AI-triaged reports in your workspace</p></CardHeader><CardContent className="flex items-center gap-2 pt-2"><div className="h-[205px] min-w-0 flex-1">{stats.isLoading ? <div className="h-full animate-pulse rounded-full bg-slate-50"/> : <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={stats.data?.bySeverity ?? []} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={57} outerRadius={82} paddingAngle={3} stroke="none">{(stats.data?.bySeverity ?? []).map(entry=><Cell key={entry.name} fill={palette[entry.name] ?? "#cbd5e1"}/>)}</Pie><Tooltip formatter={(value,name)=>[value,pretty(String(name))]} contentStyle={{ border: "1px solid #e2e8f0", borderRadius: 10, fontSize: 12 }} /></PieChart></ResponsiveContainer>}</div><div className="w-[94px] shrink-0 space-y-2.5">{["CRITICAL","HIGH","MEDIUM","LOW"].map(level=>{const value=stats.data?.bySeverity.find(item=>item.name===level)?.value ?? 0; return <div key={level}><div className="flex items-center justify-between gap-1"><span className="flex items-center gap-1.5 text-[10px] text-slate-500"><span className="h-2 w-2 rounded-full" style={{background:palette[level]}}/>{pretty(level)}</span><span className="text-[10px] font-semibold text-slate-700">{value}</span></div></div>;})}</div></CardContent></Card>
    </section>

    <section className="mt-4 grid gap-4 xl:grid-cols-2"><ChartCard title="Most common categories" subtitle="Where reports are clustering" data={stats.data?.byCategory ?? []} colorMap={palette} loading={stats.isLoading} /><ChartCard title="Priority queue" subtitle="How analyzed work is prioritized" data={stats.data?.byPriority ?? []} colorMap={palette} loading={stats.isLoading} /></section>

    <section className="mt-5 rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm shadow-slate-900/[0.02] sm:p-5"><SectionHeading title="Recently reported" href="/reports" /><div className="overflow-x-auto"><table className="w-full min-w-[680px] border-collapse text-left"><thead><tr className="border-b border-slate-100 text-[10px] uppercase tracking-wider text-slate-400"><th className="pb-3 pl-2 font-semibold">Issue</th><th className="pb-3 font-semibold">Category</th><th className="pb-3 font-semibold">Severity</th><th className="pb-3 font-semibold">Priority</th><th className="pb-3 font-semibold">Status</th><th className="pb-3 pr-2 text-right font-semibold">Created</th></tr></thead><tbody>{recent.isLoading ? Array.from({length:4},(_,i)=><tr key={i} className="border-b border-slate-50"><td colSpan={6} className="py-4"><div className="h-4 animate-pulse rounded bg-slate-50"/></td></tr>) : recent.data?.items.map(({report,summary})=><tr key={report.id} className="group border-b border-slate-50 last:border-0 hover:bg-slate-50/60"><td className="max-w-[300px] py-3.5 pl-2"><Link href={`/reports/${report.id}`} className="flex items-center gap-2.5"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-500 transition-colors group-hover:bg-indigo-50 group-hover:text-indigo-700"><Bug className="h-4 w-4"/></span><span className="truncate text-xs font-semibold text-slate-800">{report.title}</span></Link></td><td className="py-3.5 text-xs text-slate-500">{summary?pretty(summary.category):"—"}</td><td className="py-3.5"><SeverityBadge value={summary?.severity}/></td><td className="py-3.5"><PriorityBadge value={summary?.priority}/></td><td className="py-3.5"><StatusBadge value={report.status}/></td><td className="py-3.5 pr-2 text-right text-[11px] text-slate-400">{formatDate(report.createdAt)}</td></tr>)}</tbody></table></div>{!recent.isLoading&&recent.data?.items.length===0&&<div className="py-9 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Bug className="h-5 w-5"/></div><p className="mt-3 text-sm font-semibold text-slate-800">Your report queue is clear</p><p className="mt-1 text-xs text-slate-500">Capture an issue to begin building your triage history.</p><Button asChild className="mt-4 h-9 rounded-lg bg-indigo-600 text-xs"><Link href="/reports/new"><Plus className="mr-1.5 h-3.5 w-3.5"/>Create a report</Link></Button></div>}</section>

    <section className="mt-5 flex flex-col justify-between gap-4 rounded-2xl border border-indigo-100 bg-gradient-to-r from-indigo-50/80 to-white px-5 py-4 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white text-indigo-700 shadow-sm"><Sparkles className="h-4 w-4"/></div><div><p className="text-xs font-semibold text-slate-800">More reports, less copy and paste</p><p className="mt-1 text-[11px] text-slate-500">Import an issue export and let BugLens process the batch.</p></div></div><Button asChild variant="outline" className="h-9 rounded-lg border-indigo-200 bg-white text-xs font-semibold text-indigo-700 hover:bg-indigo-50"><Link href="/batch">Open batch processing <ArrowRight className="ml-2 h-3.5 w-3.5"/></Link></Button></section>
  </div></DashboardLayout>;
}

function ChartCard({title,subtitle,data,colorMap,loading}: {title:string; subtitle:string; data:{name:string;value:number}[]; colorMap:Record<string,string>; loading:boolean}) {
  const content = data.map(item=>({...item,label:item.name.replaceAll("_"," ")}));
  return <Card className="rounded-2xl border-slate-200/80 bg-white shadow-sm shadow-slate-900/[0.02]"><CardHeader className="pb-0"><CardTitle className="text-sm font-semibold text-slate-900">{title}</CardTitle><p className="mt-1 text-xs text-slate-400">{subtitle}</p></CardHeader><CardContent className="pt-4"><div className="h-[205px]">{loading?<div className="h-full animate-pulse rounded-xl bg-slate-50"/>:content.length===0?<div className="grid h-full place-items-center text-xs text-slate-400">Analyze a report to populate this chart.</div>:<ResponsiveContainer width="100%" height="100%"><BarChart data={content} layout="vertical" margin={{top:0,right:14,left:10,bottom:0}}><CartesianGrid stroke="#eef1f6" horizontal={false}/><XAxis type="number" allowDecimals={false} tick={{fill:"#94a3b8",fontSize:10}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="label" width={104} tick={{fill:"#64748b",fontSize:10}} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:"#f5f6fa"}} formatter={(value)=>[value,"Reports"]} contentStyle={{border:"1px solid #e2e8f0",borderRadius:10,fontSize:12}}/><Bar dataKey="value" radius={[0,5,5,0]} maxBarSize={20}>{content.map(entry=><Cell key={entry.name} fill={colorMap[entry.name]??"#6366f1"}/>)}</Bar></BarChart></ResponsiveContainer>}</div></CardContent></Card>;
}
