import DashboardLayout from "@/components/DashboardLayout";
import { PageHeading, StatusBadge, formatDate } from "@/components/buglens";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, Clock3, FileClock, LoaderCircle, RotateCw, XCircle } from "lucide-react";
import { Link } from "wouter";

export default function History() {
  const history=trpc.buglens.history.list.useQuery();
  return <DashboardLayout><div className="mx-auto max-w-[1180px]"><PageHeading eyebrow="Processing log" title="History" description="Every analysis attempt stays attached to its report, including retries and failures." action={<Button asChild variant="outline" className="h-9 rounded-lg border-slate-200 bg-white text-xs"><Link href="/reports"><FileClock className="mr-2 h-3.5 w-3.5"/>Report archive</Link></Button>}/>
    {history.error&&<div role="alert" className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700">{history.error.message}</div>}
    <section className="rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm sm:p-6"><div className="mb-4 flex items-center justify-between border-b border-slate-100 pb-4"><div><h2 className="text-sm font-semibold text-slate-900">Recent processing activity</h2><p className="mt-1 text-xs text-slate-400">Latest 200 saved attempts</p></div><button onClick={()=>void history.refetch()} aria-label="Refresh activity" className="grid h-8 w-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-50 hover:text-indigo-600"><RotateCw className={`h-3.5 w-3.5 ${history.isFetching?"animate-spin":""}`}/></button></div>
      {history.isLoading?<div className="space-y-3">{Array.from({length:6},(_,i)=><div key={i} className="h-[58px] animate-pulse rounded-xl bg-slate-50"/>)}</div>:!history.data?.length?<div className="py-14 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-50 text-slate-400"><Clock3 className="h-5 w-5"/></span><p className="mt-4 text-sm font-semibold text-slate-800">No processing activity yet</p><p className="mt-1 text-xs text-slate-500">Analyze a report and each processing attempt will be recorded here.</p><Button asChild className="mt-4 h-9 rounded-lg bg-indigo-600 text-xs"><Link href="/reports/new">Create a report<ArrowRight className="ml-2 h-3.5 w-3.5"/></Link></Button></div>:<div className="space-y-2">{history.data.map(({history:entry,report,batchName})=><div key={entry.id} className="flex flex-col gap-3 rounded-xl border border-slate-100 px-3.5 py-3 transition-colors hover:border-slate-200 sm:flex-row sm:items-center"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${entry.processingStatus==="SUCCESS"?"bg-emerald-50 text-emerald-600":entry.processingStatus==="FAILED"?"bg-rose-50 text-rose-600":"bg-blue-50 text-blue-600"}`}>{entry.processingStatus==="SUCCESS"?<CheckCircle2 className="h-4 w-4"/>:entry.processingStatus==="FAILED"?<XCircle className="h-4 w-4"/>:<LoaderCircle className="h-4 w-4 animate-spin"/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-xs font-semibold text-slate-800">{report?<Link href={`/reports/${report.id}`} className="hover:text-indigo-700">{report.title}</Link>:"Report no longer available"}</p><StatusBadge value={entry.processingStatus}/></div><p className="mt-1 text-[10px] text-slate-400">{batchName?`Batch · ${batchName} · `:""}{formatDate(entry.createdAt)}</p></div><div className="flex items-center gap-3 sm:ml-auto"><span className="text-[10px] text-slate-500">{entry.processingTime>0?`${(entry.processingTime/1000).toFixed(1)}s`:"—"}</span>{report&&<Button asChild variant="outline" className="h-8 rounded-lg border-slate-200 px-2.5 text-[10px]"><Link href={`/reports/${report.id}`}>Open<ArrowRight className="ml-1.5 h-3 w-3"/></Link></Button>}</div></div>)}</div>}
    </section>
  </div></DashboardLayout>;
}
