import DashboardLayout from "@/components/DashboardLayout";
import { PageHeading, PriorityBadge, SeverityBadge, StatusBadge, formatDate } from "@/components/buglens";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ArrowDownWideNarrow, ArrowLeft, ArrowRight, Bug, Eye, FilterX, LoaderCircle, Plus, RefreshCw, Search, Sparkles, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

export default function Reports() {
  const [, setLocation] = useLocation();
  const [search, setSearch] = useState("");
  const [severity, setSeverity] = useState("");
  const [priority, setPriority] = useState("");
  const [category, setCategory] = useState("");
  const [status, setStatus] = useState("");
  const [sort, setSort] = useState<"newest"|"oldest">("newest");
  const [page, setPage] = useState(1);
  const utils = trpc.useUtils();
  const queryInput = useMemo(()=>({page,pageSize:10,search,severity:severity?severity as "CRITICAL"|"HIGH"|"MEDIUM"|"LOW":undefined,priority:priority?priority as "P0"|"P1"|"P2"|"P3":undefined,category:category?category as "AUTH"|"PAYMENT"|"UI_UX"|"PERFORMANCE"|"DATA"|"API"|"SECURITY"|"INFRASTRUCTURE"|"OTHER":undefined,status:status?status as "PENDING"|"ANALYZING"|"ANALYZED"|"FAILED":undefined,sort}),[page,search,severity,priority,category,status,sort]);
  const reports=trpc.buglens.reports.list.useQuery(queryInput);
  const remove=trpc.buglens.reports.delete.useMutation({onSuccess:async()=>{toast.success("Report deleted.");await Promise.all([utils.buglens.reports.list.invalidate(),utils.buglens.dashboard.stats.invalidate()]);},onError:error=>toast.error(error.message)});
  const analyze=trpc.buglens.reports.analyze.useMutation({onSuccess:async(_,vars)=>{toast.success("Report analysis complete.");await Promise.all([utils.buglens.reports.list.invalidate(),utils.buglens.reports.detail.invalidate({id:vars.id}),utils.buglens.dashboard.stats.invalidate()]);},onError:error=>toast.error(error.message||"Unable to analyze this report.")});
  const clear=()=>{setSearch("");setSeverity("");setPriority("");setCategory("");setStatus("");setSort("newest");setPage(1);};
  const hasFilters=Boolean(search||severity||priority||category||status||sort!=="newest");
  return <DashboardLayout><div className="mx-auto max-w-[1450px]">
    <PageHeading eyebrow="Your issue archive" title="Bug reports" description="Search your reports, narrow the queue, and revisit AI triage any time." action={<Button asChild className="h-9 rounded-lg bg-indigo-600 text-xs font-semibold hover:bg-indigo-700"><Link href="/reports/new"><Plus className="mr-1.5 h-3.5 w-3.5"/>New report</Link></Button>} />
    {(reports.error)&&<div role="alert" className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-xs text-rose-700">{reports.error.message}</div>}
    <div className="rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm shadow-slate-900/[0.02] sm:p-5">
      <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="relative w-full xl:max-w-[310px]"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search title or description…" className="h-10 rounded-xl border-slate-200 pl-9 text-xs" aria-label="Search reports"/></div><div className="flex flex-wrap items-center gap-2"><FilterSelect aria="Filter by severity" value={severity} onChange={v=>{setSeverity(v);setPage(1);}} options={[["","Any severity"],["CRITICAL","Critical"],["HIGH","High"],["MEDIUM","Medium"],["LOW","Low"]]}/><FilterSelect aria="Filter by priority" value={priority} onChange={v=>{setPriority(v);setPage(1);}} options={[["","Any priority"],["P0","P0 · Urgent"],["P1","P1 · High"],["P2","P2 · Normal"],["P3","P3 · Low"]]}/><FilterSelect aria="Filter by category" value={category} onChange={v=>{setCategory(v);setPage(1);}} options={[["","Any category"],["AUTH","Authentication"],["PAYMENT","Payment"],["UI_UX","UI / UX"],["PERFORMANCE","Performance"],["DATA","Data"],["API","API"],["SECURITY","Security"],["INFRASTRUCTURE","Infrastructure"],["OTHER","Other"]]}/><FilterSelect aria="Filter by status" value={status} onChange={v=>{setStatus(v);setPage(1);}} options={[["","Any status"],["PENDING","Pending"],["ANALYZING","Analyzing"],["ANALYZED","Analyzed"],["FAILED","Failed"]]}/><button onClick={()=>setSort(value=>value==="newest"?"oldest":"newest")} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 px-3 text-[11px] font-medium text-slate-600 hover:bg-slate-50" title={`Sorted ${sort}`}><ArrowDownWideNarrow className="h-3.5 w-3.5"/>{sort==="newest"?"Newest":"Oldest"}</button>{hasFilters&&<button onClick={clear} className="inline-flex h-9 items-center gap-1 rounded-lg px-2 text-[11px] font-semibold text-slate-500 hover:bg-slate-50 hover:text-slate-900"><FilterX className="h-3.5 w-3.5"/>Clear</button>}</div></div>
      <div className="mt-4 flex items-center justify-between border-b border-slate-100 pb-3"><p className="text-[11px] text-slate-500">{reports.isLoading?"Loading reports…":<><span className="font-semibold text-slate-800">{reports.data?.total ?? 0}</span> {reports.data?.total===1?"report":"reports"} found</>}</p><button onClick={()=>void reports.refetch()} className="inline-flex items-center gap-1.5 text-[10px] font-semibold text-slate-500 hover:text-indigo-600"><RefreshCw className={`h-3 w-3 ${reports.isFetching?"animate-spin":""}`}/>Refresh</button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[840px] border-collapse text-left"><thead><tr className="border-b border-slate-100 text-[9px] uppercase tracking-wider text-slate-400"><th className="py-3 pl-2 font-semibold">Report</th><th className="py-3 font-semibold">Category</th><th className="py-3 font-semibold">Severity</th><th className="py-3 font-semibold">Priority</th><th className="py-3 font-semibold">Status</th><th className="py-3 font-semibold">Created</th><th className="py-3 pr-2 text-right font-semibold">Actions</th></tr></thead><tbody>{reports.isLoading?Array.from({length:6},(_,i)=><tr key={i} className="border-b border-slate-50"><td colSpan={7} className="py-4"><div className="h-4 animate-pulse rounded bg-slate-50"/></td></tr>):reports.data?.items.map(({report,summary})=><tr key={report.id} className="group border-b border-slate-50 last:border-0 hover:bg-slate-50/60"><td className="max-w-[280px] py-3.5 pl-2"><Link href={`/reports/${report.id}`} className="flex items-center gap-2.5"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-500 group-hover:bg-indigo-50 group-hover:text-indigo-700"><Bug className="h-4 w-4"/></span><span className="min-w-0"><span className="block truncate text-xs font-semibold text-slate-800">{report.title}</span><span className="mt-1 block truncate text-[10px] text-slate-400">{report.appModule||report.description}</span></span></Link></td><td className="py-3.5 text-[11px] text-slate-500">{summary?.category?.replaceAll("_"," ")??"—"}</td><td className="py-3.5"><SeverityBadge value={summary?.severity}/></td><td className="py-3.5"><PriorityBadge value={summary?.priority}/></td><td className="py-3.5"><StatusBadge value={report.status}/></td><td className="py-3.5 text-[10px] text-slate-400">{formatDate(report.createdAt)}</td><td className="py-3.5 pr-2"><div className="flex justify-end gap-1"><button title="View details" onClick={()=>setLocation(`/reports/${report.id}`)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-800"><Eye className="h-3.5 w-3.5"/></button><button title={summary?"Re-analyze":"Analyze"} disabled={analyze.isPending} onClick={()=>analyze.mutate({id:report.id})} className="grid h-8 w-8 place-items-center rounded-lg text-indigo-500 hover:bg-indigo-50 hover:text-indigo-700 disabled:opacity-40">{analyze.isPending?<LoaderCircle className="h-3.5 w-3.5 animate-spin"/>:<Sparkles className="h-3.5 w-3.5"/>}</button><button title="Delete report" disabled={remove.isPending} onClick={()=>{if(window.confirm(`Delete “${report.title}”? This cannot be undone.`))remove.mutate({id:report.id});}} className="grid h-8 w-8 place-items-center rounded-lg text-slate-300 hover:bg-rose-50 hover:text-rose-600 disabled:opacity-40"><Trash2 className="h-3.5 w-3.5"/></button></div></td></tr>)}</tbody></table></div>
      {!reports.isLoading&&reports.data?.items.length===0&&<div className="py-14 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-50 text-slate-400"><Search className="h-5 w-5"/></div><p className="mt-4 text-sm font-semibold text-slate-800">{hasFilters?"No reports match these filters":"No reports yet"}</p><p className="mt-1 text-xs text-slate-500">{hasFilters?"Try widening your search or clearing the filters.":"Create your first bug report to begin the triage history."}</p>{hasFilters?<Button variant="outline" onClick={clear} className="mt-4 h-9 rounded-lg text-xs">Clear filters</Button>:<Button asChild className="mt-4 h-9 rounded-lg bg-indigo-600 text-xs"><Link href="/reports/new"><Plus className="mr-1.5 h-3.5 w-3.5"/>Create report</Link></Button>}</div>}
      {!reports.isLoading&&(reports.data?.pages??0)>1&&<div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><p className="text-[10px] text-slate-400">Page {reports.data?.page} of {reports.data?.pages}</p><div className="flex gap-2"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(value=>Math.max(1,value-1))} className="h-8 rounded-lg border-slate-200 text-xs"><ArrowLeft className="mr-1.5 h-3 w-3"/>Previous</Button><Button variant="outline" disabled={page>=(reports.data?.pages??1)} onClick={()=>setPage(value=>value+1)} className="h-8 rounded-lg border-slate-200 text-xs">Next<ArrowRight className="ml-1.5 h-3 w-3"/></Button></div></div>}
    </div>
  </div></DashboardLayout>;
}

function FilterSelect({aria,value,onChange,options}:{aria:string;value:string;onChange:(value:string)=>void;options:string[][]}) {return <select aria-label={aria} value={value} onChange={e=>onChange(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-2.5 text-[10px] font-medium text-slate-600 outline-none focus:border-indigo-300 focus:ring-2 focus:ring-indigo-100">{options.map(([id,label])=><option key={label} value={id}>{label}</option>)}</select>}
