import DashboardLayout from "@/components/DashboardLayout";
import { PageHeading, PriorityBadge, SeverityBadge, StatusBadge, formatDate } from "@/components/buglens";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, Clipboard, Clock3, FileText, LoaderCircle, Pencil, RefreshCw, ShieldCheck, Sparkles, Trash2, WandSparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { toast } from "sonner";

export default function ReportDetail() {
  const [, params] = useRoute("/reports/:id");
  const reportId = Number(params?.id);
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const detail = trpc.buglens.reports.detail.useQuery({id:reportId},{enabled:Number.isInteger(reportId)&&reportId>0,retry:false});
  const [editing,setEditing]=useState(false);
  const [title,setTitle]=useState("");
  const [description,setDescription]=useState("");
  const [environment,setEnvironment]=useState("");
  const [module,setModule]=useState("");
  useEffect(()=>{if(detail.data){setTitle(detail.data.report.title);setDescription(detail.data.report.description);setEnvironment(detail.data.report.environment??"");setModule(detail.data.report.appModule??"");}},[detail.data]);
  const update=trpc.buglens.reports.update.useMutation({onSuccess:async()=>{toast.success("Report updated.");setEditing(false);await Promise.all([utils.buglens.reports.detail.invalidate({id:reportId}),utils.buglens.reports.list.invalidate(),utils.buglens.dashboard.stats.invalidate()]);},onError:error=>toast.error(error.message)});
  const analyze=trpc.buglens.reports.reanalyze.useMutation({onSuccess:async()=>{toast.success("Fresh analysis is ready.");await Promise.all([utils.buglens.reports.detail.invalidate({id:reportId}),utils.buglens.reports.list.invalidate(),utils.buglens.dashboard.stats.invalidate()]);},onError:error=>toast.error(error.message||"Unable to analyze this report.")});
  const remove=trpc.buglens.reports.delete.useMutation({onSuccess:async()=>{toast.success("Report deleted.");await utils.buglens.reports.list.invalidate();setLocation("/reports");},onError:error=>toast.error(error.message)});
  const report=detail.data?.report;
  const summary=detail.data?.summary;
  if(detail.isLoading)return <DashboardLayout><div className="mx-auto max-w-[1080px] animate-pulse"><div className="h-4 w-28 rounded bg-slate-200"/><div className="mt-4 h-9 w-2/3 rounded bg-slate-200"/><div className="mt-7 h-48 rounded-2xl bg-white"/><div className="mt-4 h-80 rounded-2xl bg-white"/></div></DashboardLayout>;
  if(detail.error||!report)return <DashboardLayout><div className="mx-auto max-w-[700px] rounded-2xl border border-slate-200 bg-white p-8 text-center"><p className="text-sm font-semibold text-slate-800">Report unavailable</p><p className="mt-2 text-xs text-slate-500">{detail.error?.message||"This report may have been removed or may not belong to your account."}</p><Button asChild variant="outline" className="mt-5 rounded-lg"><Link href="/reports"><ArrowLeft className="mr-2 h-3.5 w-3.5"/>Back to reports</Link></Button></div></DashboardLayout>;
  const copySummary=async()=>{if(!summary)return;try{await navigator.clipboard.writeText(summary.summary);toast.success("Summary copied to clipboard.");}catch{toast.error("Could not access the clipboard.");}};

  return <DashboardLayout><div className="mx-auto max-w-[1080px]">
    <PageHeading eyebrow={`Bug report · #${report.id}`} title={report.title} description={`${report.appModule||"Uncategorized module"} · Created ${formatDate(report.createdAt)}`} action={<div className="flex flex-wrap items-center gap-2"><Button asChild variant="outline" className="h-9 rounded-lg border-slate-200 bg-white text-xs"><Link href="/reports"><ArrowLeft className="mr-1.5 h-3.5 w-3.5"/>All reports</Link></Button><Button variant="outline" disabled={analyze.isPending} onClick={()=>analyze.mutate({id:reportId})} className="h-9 rounded-lg border-indigo-200 bg-white text-xs font-semibold text-indigo-700 hover:bg-indigo-50">{analyze.isPending?<LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin"/>:<RefreshCw className="mr-1.5 h-3.5 w-3.5"/>}{summary?"Re-analyze":"Analyze"}</Button><Button variant="outline" onClick={()=>{if(window.confirm(`Delete “${report.title}”? This cannot be undone.`))remove.mutate({id:reportId});}} disabled={remove.isPending} className="h-9 rounded-lg border-rose-200 bg-white text-xs text-rose-600 hover:bg-rose-50"><Trash2 className="mr-1.5 h-3.5 w-3.5"/>Delete</Button></div>}/>
    <div className="mb-5 flex flex-wrap items-center gap-2"><StatusBadge value={report.status}/>{report.reportedSeverity&&<><span className="text-[10px] text-slate-400">Reporter assessment</span><SeverityBadge value={report.reportedSeverity}/></>}</div>
    <section className="grid gap-4 lg:grid-cols-[0.92fr_1.08fr]">
      <Card className="h-fit rounded-2xl border-slate-200/80 bg-white shadow-sm"><CardHeader className="flex flex-row items-center justify-between border-b border-slate-100 pb-4"><div><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-slate-600"><FileText className="h-4 w-4"/></span><CardTitle className="text-sm">Original report</CardTitle></div><p className="mt-2 text-[10px] text-slate-400">User-provided · source content</p></div><Button variant="outline" size="sm" onClick={()=>setEditing(value=>!value)} className="h-8 rounded-lg border-slate-200 text-[10px]"><Pencil className="mr-1.5 h-3 w-3"/>{editing?"Cancel edit":"Edit details"}</Button></CardHeader><CardContent className="p-5">
        {editing?<form onSubmit={event=>{event.preventDefault();update.mutate({id:reportId,title,description,environment,appModule:module});}} className="space-y-4"><label className="block space-y-1.5 text-xs font-semibold text-slate-700">Title<Input value={title} maxLength={255} onChange={e=>setTitle(e.target.value)} required minLength={3} className="h-10 rounded-lg text-xs font-normal"/></label><label className="block space-y-1.5 text-xs font-semibold text-slate-700">Description<Textarea value={description} maxLength={20000} onChange={e=>setDescription(e.target.value)} required minLength={10} className="min-h-36 rounded-lg text-xs font-normal leading-5"/></label><label className="block space-y-1.5 text-xs font-semibold text-slate-700">Environment<Input value={environment} maxLength={1000} onChange={e=>setEnvironment(e.target.value)} className="h-9 rounded-lg text-xs font-normal"/></label><label className="block space-y-1.5 text-xs font-semibold text-slate-700">Module<Input value={module} maxLength={120} onChange={e=>setModule(e.target.value)} className="h-9 rounded-lg text-xs font-normal"/></label><Button type="submit" disabled={update.isPending} className="h-9 rounded-lg bg-indigo-600 text-xs">{update.isPending?<LoaderCircle className="mr-2 h-3.5 w-3.5 animate-spin"/>:<Check className="mr-2 h-3.5 w-3.5"/>}Save changes</Button></form>:<><div className="rounded-xl bg-slate-50/80 p-4"><p className="whitespace-pre-wrap text-xs leading-6 text-slate-700">{report.description}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Meta label="Environment" value={report.environment}/><Meta label="Application / module" value={report.appModule}/><Meta label="Created" value={formatDate(report.createdAt)}/><Meta label="Updated" value={formatDate(report.updatedAt)}/></div>{report.rawText!==report.description&&<details className="mt-4"><summary className="cursor-pointer text-[10px] font-semibold text-indigo-600">View normalized source text</summary><pre className="mt-2 whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-[10px] leading-5 text-slate-600">{report.rawText}</pre></details>}</>}
      </CardContent></Card>

      <Card className="overflow-hidden rounded-2xl border-indigo-100 bg-white shadow-sm"><CardHeader className="border-b border-indigo-100 bg-gradient-to-r from-indigo-50/90 to-white pb-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white text-indigo-700 shadow-sm"><Sparkles className="h-4 w-4"/></span><CardTitle className="pt-1 text-sm">AI-generated triage</CardTitle></div><p className="mt-2 text-[10px] text-slate-500">Structured analysis · validate against your product context</p></div>{summary&&<Button onClick={()=>void copySummary()} variant="outline" className="h-8 shrink-0 rounded-lg border-indigo-100 bg-white text-[10px] text-indigo-700"><Clipboard className="mr-1.5 h-3 w-3"/>Copy summary</Button>}</div></CardHeader><CardContent className="p-5">
        {!summary?<div className="flex flex-col items-center py-9 text-center"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${report.status==="FAILED"?"bg-rose-50 text-rose-600":"bg-indigo-50 text-indigo-600"}`}>{report.status==="FAILED"?<RefreshCw className="h-5 w-5"/>:<WandSparkles className="h-5 w-5"/>}</span><p className="mt-4 text-sm font-semibold text-slate-800">{report.status==="ANALYZING"?"Analysis in progress":report.status==="FAILED"?"The last analysis did not complete":"Ready to analyze"}</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-500">{report.status==="ANALYZING"?"Refresh in a moment to see the result.":"Run a backend AI analysis to generate severity, priority, reproduction steps and a recommended action."}</p>{report.status!=="ANALYZING"&&<Button disabled={analyze.isPending} onClick={()=>analyze.mutate({id:reportId})} className="mt-5 h-9 rounded-lg bg-indigo-600 text-xs">{analyze.isPending?<LoaderCircle className="mr-2 h-3.5 w-3.5 animate-spin"/>:<Sparkles className="mr-2 h-3.5 w-3.5"/>}Analyze this report</Button>}</div>:<div>
          <div className="rounded-xl border border-indigo-100 bg-indigo-50/50 p-4"><div className="mb-2 flex items-center gap-1.5 text-[9px] font-semibold uppercase tracking-wider text-indigo-600"><Sparkles className="h-3 w-3"/>Concise summary</div><p className="text-sm font-medium leading-6 text-slate-800">{summary.summary}</p></div>
          <div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-xl border border-slate-100 bg-white p-3"><p className="mb-2 text-[9px] font-semibold uppercase tracking-wider text-slate-400">Severity</p><SeverityBadge value={summary.severity}/></div><div className="rounded-xl border border-slate-100 bg-white p-3"><p className="mb-2 text-[9px] font-semibold uppercase tracking-wider text-slate-400">Priority</p><PriorityBadge value={summary.priority}/></div><div className="rounded-xl border border-slate-100 bg-white p-3"><p className="mb-2 text-[9px] font-semibold uppercase tracking-wider text-slate-400">Category</p><span className="text-[10px] font-semibold text-slate-700">{summary.category.replaceAll("_"," ")}</span></div></div>
          <div className="mt-4 space-y-3"><SummaryBlock title="Impact" value={summary.impact}/><SummaryBlock title="Steps to reproduce" value={<ol className="list-decimal space-y-1.5 pl-4">{summary.stepsToReproduce.map((step,index)=><li key={`${step}-${index}`}>{step}</li>)}</ol>}/><SummaryBlock title="Expected behavior" value={summary.expectedBehavior}/><SummaryBlock title="Actual behavior" value={summary.actualBehavior}/><SummaryBlock title="Environment" value={summary.environment}/><SummaryBlock title="Possible root cause" value={summary.possibleRootCause}/><SummaryBlock title="Recommended action" value={summary.recommendedAction}/></div>
          <div className="mt-4 flex items-start gap-2 rounded-xl border border-slate-100 bg-slate-50 p-3"><ShieldCheck className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-500"/><p className="text-[10px] leading-5 text-slate-500">AI output is a triage aid, not a verified root-cause diagnosis. Review it with the original report before prioritizing changes.</p></div>
          <div className="mt-3 flex items-center justify-between text-[9px] text-slate-400"><span className="flex items-center gap-1"><Clock3 className="h-3 w-3"/>Generated {formatDate(summary.createdAt)}</span><span className="flex items-center gap-1"><ShieldCheck className="h-3 w-3"/>Validated structured output</span></div>
        </div>}
      </CardContent></Card>
    </section>
    {report.status==="ANALYZING"&&<button onClick={()=>void detail.refetch()} className="mt-4 inline-flex items-center gap-1.5 text-[11px] font-semibold text-indigo-600"><RefreshCw className="h-3 w-3"/>Refresh status</button>}
  </div></DashboardLayout>;
}

function Meta({label,value}:{label:string;value:string|null|undefined}){return <div className="rounded-lg border border-slate-100 px-3 py-2.5"><p className="text-[9px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 truncate text-[10px] font-medium text-slate-700">{value||"Not provided"}</p></div>}
function SummaryBlock({title,value}:{title:string;value:React.ReactNode}){return <div className="rounded-xl border border-slate-100 px-4 py-3"><h3 className="text-[10px] font-semibold text-slate-800">{title}</h3><div className="mt-1.5 text-[11px] leading-5 text-slate-600">{value}</div></div>}
